### ISSUE TITLE
Enhancement : Adding global trafic information

### ISSUE THREAD

**Issue by Tatroxitum** [da4throux/MMM-Paris-RATP-PG#14]
Idea : add global trafic information of all lines or a specific line (user choice)

**Comment by da4throux** [comment]
Hi thanks for the idea.
The API can give traffic status for RERs, subways ([https://api-ratp.pierre-grimaud.fr/v3/traffic](https://api-ratp.pierre-grimaud.fr/v3/traffic) ). I do not really have the use case (like the RER B line often have alerts but in the ends it's very rare they are relevant). Can you tell me more about yours, and if you have views on how it could look like ?
thanks

**Comment by Tatroxitum** [comment]
Salut,

Dans mon idée il est intéressant de savoir si tout va bien ("slug":
"normal", "title": "Trafic normal") ou s'il y a des alertes (par exemple ce
matin sur le B justement "slug": "critique", "title": "Trafic trÃ¨s
perturbÃ©") et "slug": "alerte", "title": "Trafic perturbÃ©",
Les travaux peuvent être considérés comme traffic normal ("slug":
"normal_trav", "title": "Travaux").

Mon use case, en prenant l'exemple concret de ce matin : ça aurait permis à
ma femme de ne pas aller jusqu'à la gare mais directement de prendre le bus
;).

Je verrais bien : une ligne entre le rafraichissement et les horaires
indiquant :
- "Traffic normal sur l'ensemble des lignes" dans le cas où tous les slug
sont à la valeur "normal" ou "normal_trav",
-  et dans le cas où un slug est à "critique" ou "alerte" l'afficher à la place, en
concaténant la "line" et le message : "ligne B : 02/05/17, 07:11, le trafic
est trÃ¨s fortement perturbÃ© sur la ligne (accident grave de voyageur)"
(ça m'étonnerais qu'il y ai plus de deux critiques, prévoir deux lignes
donc).

Il me semble qu'il est aussi possible d'envoyer l'info sur le module
"alert", ça peut être une autre manière de faire où l'on envoi l'info que
lors du cas "critique" ou "alerte".
Dispo pour toute question !


Cordialement,

Damien.

**Comment by da4throux** [comment]
Hi,

I think version 1.5 should fulfill this need :) 
reading again the request, I think it does not go as far as you want yet... here you have to set it up for each line you want to monitor. I thought that was better because in my case I'll monitor RER A, but not B because there's very rarely a message that is relevant for me.

Might be worth to add an option to not display the status if everything is fine, no ?

hope that works for you

**Comment by Tatroxitum** [comment]
Hi,

Thanks for the good works !

You're right, rarely people monitor more than two lines so I think the need is fulfilled.
An option to hide when "normal" could be interesting, or put a color on alert level (ie red for "critical" and yellow for "alert").

**Comment by Tatroxitum** [comment]
Oups! I did not intended to close it, but you can close the issue if you want.

**Comment by da4throux** [comment]
It was ok if you closed it, not sure what the github-etiquette is.

thanks
