### ISSUE TITLE
subway metro times

### ISSUE THREAD

**Issue by d31r** [da4throux/MMM-Paris-RATP-PG#15]
Hello,

Great module!
I wanted to know if it might be possible for you to add the metro times as well?
I've tried to do it mais je suis une merde en programmation!

I was thinking about something basic, like the next two metros for a station for a specific direction.
If you have the time and energy, of course!

Thanks,

**Comment by da4throux** [comment]
Hi,

thanks for the feedback, just added support for metro stations in version 1.4 👍
