### ISSUE TITLE
Metro configuration

### ISSUE THREAD

**Issue by mab173** [da4throux/MMM-Paris-RATP-PG#28]
Hello,
First, thanks a lot for this module! 

I tried to write a configuration for a metro station but it still shows me the same message on the mirror: 
"Configuration now requires a 'lines' element. Check github da4throux/MMM-Paris-RATP-PG for more information."

Here's my configuration tentative:
module: "MMM-Paris-RATP-PG",
position: "top_bar",
header: "RATP",
config: {
           busStations: [
                        {api: "v3", type: "metros", line: "7", stations: "tolbiac", destination: "A"},
                        {api: "v3", type: "traffic", line: ["metros", "7"]}
           ]
}

Is there something wrong?

Thank you for your help!

**Comment by da4throux** [comment]
Hi,
indeed there is something wrong. 
But it's mainly my fault.
When re-writing the code for v2, I required a strong change in the configuration, which would require people migrating from v1 to change their configuration.
I updated the code so that the module still works in that case (at least for v3 api settings ...
So if you update the module it should work, but still, my recommendation would be to update your configuration at least to:
module: "MMM-Paris-RATP-PG",
position: "top_bar",
header: "RATP",
config: {
lines: [
{type: "metros", line: "7", stations: "tolbiac", destination: "A"},
{type: "traffic", line: ["metros", "7"]}
]
}

and maybe take a look, if you want to add colors, or see if it's going to rain in the next hour (useful when you leave home) information 😄

**Comment by mab173** [comment]
Thank you for this fast answer!
So I updated the module and put the new config. 
I don't know if the mirror magic is on or not, but the mirror screen becomes black and I just can see the yellow lightning symbol and the mouse cursor. 
It makes me that every times I change "busStations" (or an other word) with "lines"

**Comment by da4throux** [comment]
Sorry for that, it's my module failing for sure.
- does the configuration above work ?
- if yes, I assume you are using another configuration, can you post it ?

thanks

**Comment by mab173** [comment]
I wrote:

module: "MMM-Paris-RATP-PG",
position: "top_bar",
header: "RATP",
config: {
lines: [
{type: "metros", line: "7", stations: "tolbiac", destination: "A"}
]
}

**Comment by da4throux** [comment]
Hmmm that config works fine on my side. I can see subways for Mairie d'Ivry or Villejuif-Louis Aragon.
Either the module is not up-to-date. To be sure, maybe do a 'git pull' in the module directory ?
or there is another error in the  config file ? I can take a look if you share me the whole file.

**Comment by mab173** [comment]
_What I did to update:_
pi@berryberry:~/MagicMirror/modules/MMM-Paris-RATP-PG $ cd $HOME
pi@berryberry:~ $ cd $HOME/MagicMirror/modules/MMM-Paris-RATP-PG
pi@berryberry:~/MagicMirror/modules/MMM-Paris-RATP-PG $ git pull
Déjà à jour.
pi@berryberry:~/MagicMirror/modules/MMM-Paris-RATP-PG $ npm install
pi@berryberry:~/MagicMirror/modules/MMM-Paris-RATP-PG $

_What I did on the config file (the previous part is unchanged):_
language: "fr",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Vacances scolaires",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "http://www.education.gouv.fr/download.php?file=http://cache.media.education.gouv.fr/ics/Calendrier_Scolaire_Zones_A_B_C.ics"
					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third",
			config: {
				compliments: {
					anytime: [
						"~Bonjour~"
					],
					morning: [		
						"J'apporte tout de suite votre bol de chocapic!"
					],
					afternoon: [
						"J'ai faim, donnez moi des pixels à manger!",					
					]								
				}
			}			
		},
		{
			module: "currentweather",
			position: "top_right",
						config: {
				location: "Paris",
				locationID: "6455259",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "xxxxxxxxxxxxxxxxxxxxx"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Prévisions météo",
			config: {
				location: "Paris",
				locationID: "6455259",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "xxxxxxxxxxxxxxxxxxxxx"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "Le Figaro",
						url: "http://www.lefigaro.fr/rss/figaro_flash-actu.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
		{
	        	module: "MMM-Paris-RATP-PG",
	       		position: "bottom_right",
	       		header: "RATP",	       	
			config: {
				lines: [
					{type: "metros", line: "7", stations: "tolbiac", destination: "A"}
				]
			}		
    		},				
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by da4throux** [comment]
Hi, 
the beginning of your config file is missing, and the layout in github seems strange (but I guess it is bound to be... ). Out of curiosity could you try this one:
--------beginning
/* Magic Mirror Config Sample 
 * 
 * By Michael Teeuw http://michaelteeuw.nl 
 * MIT Licensed. 
 */ 

var config ={  
   port:8080,
   address:"0.0.0.0",
   language:'fr',
   timeFormat:24,
   units:'metric',
   modules:[  
      {  
         module:'alert',
      },
      {  
         module:"updatenotification",
         position:"top_bar",
      },
      {  
         module:'clock',
         position:'top_left',
      },
      {  
         module:"calendar",
         header:"Vacances scolaires",
         position:"top_left",
         config:{  
            calendars:[  
               {  
                  symbol:"calendar-check-o ",
                  url:"http://www.education.gouv.fr/download.php?file=http://cache.media.education.gouv.fr/ics/Calendrier_Scolaire_Zones_A_B_C.ics"
               }
            ]
         }
      },
      {  
         module:"compliments",
         position:"lower_third",
         config:{  
            compliments:{  
               anytime:[  
                  "~Bonjour~"
               ],
               morning:[  
                  "J'apporte tout de suite votre bol de chocapic!"
               ],
               afternoon:[  
                  "J'ai faim, donnez moi des pixels à manger!",
               ]
            }
         }
      },
      {  
         module:"currentweather",
         position:"top_right",
         config:{  
            location:"Paris",
            locationID:"6455259",
            //ID from http:            //www.openweathermap.org/help/city_list.txt 
appid:"xxxxxxxxxxxxxxxxxxxxx"
         }
      },
      {  
         module:"weatherforecast",
         position:"top_right",
         header:"Prévisions météo",
         config:{  
            location:"Paris",
            locationID:"6455259",
            //ID from http:            //www.openweathermap.org/help/city_list.txt 
appid:"xxxxxxxxxxxxxxxxxxxxx"
         }
      },
      {  
         module:"newsfeed",
         position:"bottom_bar",
         config:{  
            feeds:[  
               {  
                  title:"Le Figaro",
                  url:"http://www.lefigaro.fr/rss/figaro_flash-actu.xml"
               }
            ],
            showSourceTitle:true,
            showPublishDate:true
         }
      },
      {  
         module:"MMM-Paris-RATP-PG",
         position:"bottom_right",
         header:"RATP",
         config:{  
            lines:[  
               {  
                  type:"metros",
                  line:"7",
                  stations:"tolbiac",
                  destination:"A"
               }
            ]
         }
      },
   ]
}; 

/*************** DO NOT EDIT THE LINE BELOW ***************/ 
if (typeof module !== 'undefined'){  
   module.exports = config;
}

-------------end
It worked on my side

**Comment by mab173** [comment]
Hello, sorry for the late,
So I tried with your new config and it's still the same problem again...Maybe the problem is my actual monitor... I will try to change the monitor...
Thanks for you help

**Comment by da4throux** [comment]
Ok, you're confusing me a bit.
Troubleshooting procedure would be that, you add/ remove the module configuration block and you check if it works or not. If it's not working without the module in your config file, you should go back to even a more basic file.
Regarding the monitor, it should be obvious when starting the pi, I would think.
You can find more help also on the MMM forum I think.
Don't hesitate to tell me when you are back on track if you need help.
For the time being I'm closing the issue.
