### ISSUE TITLE
Écran noir :(

### ISSUE THREAD

**Issue by bobby40413** [da4throux/MMM-Paris-RATP-PG#29]
Bonjour, 
Je rencontre un problème et je voudrais savoir si vous pouvez m'aider.

Tout d'abord je voudrais juste vous signaler que je débute.

J'ai installer Magic Mirror sur Windows 10 en utilisant ce tuto :

https://forum.magicmirror.builders/topic/4089/complete-walkthrough-install-magicmirror-on-a-pc-windows-7-10

Tout fonctionne nickel jusqu'à présent, mais dès que je tente de mettre votre module j'ai un écran noir complet, même les module d'origine n'apparaissent plus.

Dès que j'enlève votre module tout reviens dans l'ordre.

Avez-vous une idée de quel parti je fais Mal ou à quel moment je me trompe ?

Merci d'avance pour votre aide.

**Comment by da4throux** [comment]
Bonjour,
de mon expérience c'est un problème dans la config à priori.
Donc je suggère: de poster une config la plus simple possible qui ne marche pas (en partant de la config la plus minimale qui marche, rajouter celle du module).
Les logs du lanceur et de la console du browser peuvent sûrement aider, et en dernière instance rajouter debug: true dans la config pour logger plus que d'habitude.

merci d'avance

**Comment by aphentik** [comment]
Hello,
Trying since 3 days without success, I still have a black screen :/. Is the module supposed to work ?
Regards

En français aussi si jamais c'est plus simple !

Edit : RESOLVED
Seems to be linked to "unirest" module 
--> .pm2/logs/mm-error-0.log
```
Error: Cannot find module 'unirest'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/$
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Paris-RATP-PG/node_helpe$
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Paris-RATP-PG/node_helpe$
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```
I've tried various things but finally fix it with
`sudo npm install unirest`

**Comment by da4throux** [comment]
Hi aphentik,

thanks a lot for the debug !
I'll investigate a bit to confirm the dependency and add it so that it is installed automatically

cheers

**Comment by tarto-dev** [comment]
Salut. J'ai également installé ça sous windows et j'ai également rencontré le soucis de black-screens. Comme le suggère @da4throux il s'agit très probablement d'un soucis de config. C'était le cas pour moi ;) 

Partage ta config qu'on t'aide à y voir plus clair :)

**Comment by aphentik** [comment]
Hello,
As said above it was an issue due to a bad/not installed unirest module. Without changing anything on the config file, a basic sudo `npm install unirest` fixed the issue. 

Regards,

**Comment by da4throux** [comment]
I close the issue, it seems solved :D
