### ISSUE TITLE
RER: comment filter les missions des trains?

### ISSUE THREAD

**Issue by Oeil2L** [da4throux/MMM-Paris-RATP-PG#31]
Bonjour,

N'ayant pas réussi à installer un environnement de Debug et n'étant pas doué en javascript, je tente ma chance ici.

Lorsque sa gare de destination se situe sur la partie centrale du RER, la direction d'une ligne RER suffit.

Par contre, lorsque l'on se rend à un gare dans l'une des branches d'une ligne RER ou quand sa gare de destination n'est pas desservi systématiquement (train non omnibus), il faudrait filtrer les horaires des trains pour une ou plusieurs destinations bien précises.

Par exemple sur le RER A, un départ de La Défense vers Sartrouville, seul les trains dont le code mission aurait comme 1ère lettre U,I,T,A,V seraient acceptable, la branche Saint-Germain n'est pas utile:
https://rera-leblog.fr/wp-content/uploads/2017/07/Ligne_A_sch%C3%A9ma_de_la_ligne-modif2.jpg

Et pour les non omnibus, les 2 premières lettres sont à considérer:
https://rera-leblog.fr/les-codes-missions-des-rer-a-dechiffres/

L'api renvoie déjà les codes missions, il "suffirait" de filtrer les bons code mission:
> {
>     "result": {
>         "schedules": [
>             {
>                 "code": "ZUME",
>                 "message": "23:49 Voie 2",
>                 "destination": "Saint-Germain-en-Laye"
>             },
>             {
**>                 "code": "TAXE",
>                 "message": "00:01 Voie 2C",
>                 "destination": "Poissy"**
>             },
>             {
>                 "code": "ZURE",
>                 "message": "00:06 Voie 2",
>                 "destination": "Saint-Germain-en-Laye"
>             },
>             {
**>                 "code": "VETO",
>                 "message": "00:12 Voie 2C",
>                 "destination": "Sartrouville"**
>             },
>             {
>                 "code": "ZURE",
>                 "message": "00:19 Voie 2",
>                 "destination": "Saint-Germain-en-Laye"
>             },
>             {
**>                 "code": "TAXI",
>                 "message": "00:25 Voie 2C",
>                 "destination": "Poissy"**
>             },
>             {
>                 "code": "ZURE",
>                 "message": "00:31 Voie 2",
>                 "destination": "Saint-Germain-en-Laye"
>             },
>             {
**>                 "code": "VIRA",
>                 "message": "00:37 Voie 2C",
>                 "destination": "Sartrouville"**
>             },
>             {
>                 "code": "ZEBU",
>                 "message": "00:45 Voie 2",
>                 "destination": "Saint-Germain-en-Laye"
>             },
>             {
**>                 "code": "TEDI",
>                 "message": "00:52 Voie 2C",
>                 "destination": "Poissy"**
>             },
>             {
>                 "code": "ZEBU",
>                 "message": "00:57 Voie 2",
>                 "destination": "Saint-Germain-en-Laye"
>             }
>         ]
>     },
>     "_metadata": {
>         "call": "GET /schedules/rers/A/nanterre+prefecture/A",
>         "date": "2019-02-21T23:44:12+01:00",
>         "version": 3
>     }
> }

Merci par avance

**Comment by da4throux** [comment]
C'est une très bonne idée, je vais travailler sur cela tout de suite.

**Comment by da4throux** [comment]
J'ai ajouté la fonction dans la 2.5, n'étant pas utilisateur j'ai un peu testé, mais si tu peux regarder c'est top, en attendant je ferme la demande
merci :D
