### ISSUE TITLE
Pas d'infos sur lignes metro et RER paris

### ISSUE THREAD

**Issue by tet102** [da4throux/MMM-Paris-RATP-PG#33]
Bonjour, 
j'utilise votre Module et je n'arrive pas à avoir les infos concernant le traffic concernant les lignes de metro et sur certaines lignes RER A et B. 
Auriez-vous une idée svp ?
extrait du config.sys
{type: 'traffic', line: ["metros", "13"]},
et image pour montrer ce que j'ai comme affichage de votre module.
![Untitled 1](https://user-images.githubusercontent.com/33205971/67986781-1a35ba00-fc2c-11e9-9e84-1d1947e97e97.png)
Je trouve que c'est un super module et je m'en sers mais il me manque cruellement le traffic concernant la ligne 13 par exemple.
MErci pour votre réponse salutations.
Stéphane

**Comment by da4throux** [comment]
Bonjour Stéphane,

oui tu as raison, j'ai le même soucis de mon côté, je vais creuser (autant côté vélib je suis moins motivé), autant cet élément devrait marcher.

merci de ton retour,
Damien

**Comment by da4throux** [comment]
Je viens de mettre à jour e. 2.4, je pense que c'est bon maintenant, si tu peux essayer de ton côté c'est top !

**Comment by da4throux** [comment]
Ça à l'air bon de mon côté, je clos l'issue en attendant, mais n'hésite pas si c'est pas bon

**Comment by tet102** [comment]
![image](https://user-images.githubusercontent.com/33205971/68058941-fab99280-fcfa-11e9-9cf7-8358be87a750.png)

C'est parfait encore merci pour ton travail et ta rapidité pour la correction. Génial
