### ISSUE TITLE
Support Vélib Métropole

### ISSUE THREAD

**Issue by robestial** [da4throux/MMM-Paris-RATP-PG#34]
Bonjour,

Tout d'abord, félicitations pour cet excellent module!

Depuis quelque temps le module n'affiche pas bien la disponibilité des stations vélib:
![image](https://user-images.githubusercontent.com/50526917/68024998-fdd96200-fcab-11e9-8b9d-98a2b4e93c8a.png)

Je pense qu'à cause du changement de l'ancien vélib au nouveau vélib métropole, les messages envoyés contre l'API ne sont plus bien composés et les champs demandés ne correspondent pas à ceux qu'il faudrait attaquer.

Par exemple, en regardant le fichier .js je vois:
- if (d.data && d.data['is_renting'] === 1) {
- secondCell.innerHTML = d.data['numbikesavailable']
- secondCell.innerHTML += d.data['numdocksavailable']

Or la structure de l'API contient les champs suivants:
"station_state", "nbfreeedock", "nbfreedock", "nbbike", "nbebike"...

Je ne me connais pas énormément en javascript et par conséquent je ne sais pas trop comment modifier le code, mais je pense qu'il faudrait mettre à jour pour supporter la nouvelle API qui inclut les vélibs électriques.

Ou peut-être c'est ma version du module qui n'est pas à jour?

Merci bien par avance,
Roberto

**Comment by da4throux** [comment]
Bonjour Roberto,

merci et en effet ton analyse est bonne, depuis le changement d'opérateur vélibs, cette fonction n'est plus disponible. Je les avais contacté au début pour savoir quand est-ce que ce serait disponible, mais ils étaient, à juste titre, plus préoccupés de travailler sur la qualité du service.
Aujourd'hui, en tant qu'utilisateur, je dois avouer que la qualité du service n'est toujours pas là, et je ne me suis pas repenché sur le sujet.
Et d'ailleurs je n'ai pas travaillé sur ce module depuis longtemps. Je te garantie rien (et si d'autres personnes sont intéressées n'hésitez pas à commenter aussi), je vais jeter un oeil :D

cordialement,
Damien

**Comment by tet102** [comment]
Damien, magicMirror a sacrément évolué depuis 2 ans. Et je pense que quand j'aurais finis ma config. Je vais faire une vidéo sur Youtube et je pense que beaucoup de parisiens seraient intéressé de connaitre l'état du Trafic et des dispos de leurs stations vélib.
Je pense que la MAJ est nécéssaire depuis ces 2 ans passées.
Encore merci pour ton JOB, 
Cordialement
Stef

**Comment by robestial** [comment]
Hello Damien,

Merci pour ta réponse, j'espère que tu trouveras le temps pour ça (profite quand même du jour férié!)
Comme Stef dit, il doit y avoir plein de monde intéressé!

Bonne soirée,
Roberto

**Comment by da4throux** [comment]
Les amis, ça devrait être bon !
en tout cas de mon côté ça marche, par contre faîte attention au numéro de station dans la configuration... j'aurai d'ailleurs dû faire une version majeure, plus que mineure (2.6).
Dites moi si ça marche de votre côté aussi.
Et par curiosité, utilisez vous le graph ? (je trouve ça super, mais ça prend beaucoup de place, et c'est pas très esthétique).
J'attends vos retours avant de fermer cette issue.

**Comment by robestial** [comment]
Bonjour Damien,

Je confirme, ça marche aussi pour moi!
![image](https://user-images.githubusercontent.com/50526917/68071258-f9c74600-fd78-11e9-8947-46865f517217.png)

Quant au graph, effectivement il prend trop de place donc je ne l'utilise pas.

Merci encore pour ton aide!

Bon WE,
Roberto

**Comment by tet102** [comment]
Ca marche aussi pour moi, Merci encore Damien...
Tu es au top

**Comment by robestial** [comment]
Bonjour @da4throux ,

J'espère que tu vas bien!

Je t'écris pour signaler que le problème est à nouveau présent.

J'ai un peu regardé et je pense que les éléments suivants ont changé:
1. Le champ de filtrage "station_code" est maintenant "stationcode"
2. "nbebike" est maintenant "ebike"
3. "nbbike" est maintenant "mechanical"
4. "nbfreeedock" et "nbfreedock" sont maintenant "numdocksavailable"

Peut-être qu'il y a d'autres éléments à regarder, mais j'espère au moins t'avoir simplifié le travail.

Merci encore une fois pour ton aide,
Roberto

**Comment by da4throux** [comment]
Merci je vais essayer de regarder maintenant.

**Comment by da4throux** [comment]
merci beaucoup @robestial cela m'a fait gagné du temps les informations.
il y avait également: capacity, et station_state.

Je pense que c'est bon si tu peux confirmer de ton côté c'est top.
merci !

**Comment by robestial** [comment]
Hello @da4throux ,

J'ai pu confirmer de mon côté et c'est bon!
![image](https://user-images.githubusercontent.com/50526917/76739783-00c18480-676d-11ea-9615-e5a95d4498da.png)

Merci pour ton aide, il va peut-être falloir que je commence à toucher le code pour éviter de te donner du travail à chaque fois que l'API change.

Bonne semaine!

**Comment by da4throux** [comment]
Toujours bien de rentrer dans le code, mais pas de soucis, c'est vraiment
top comme ça.
Best Practice: rouvrir l'Issues, car ça m'aide à voir plus facilement qu'il
y a un problème.


merci encore !!!
