### ISSUE TITLE
Ecran noir

### ISSUE THREAD

**Issue by franekola** [da4throux/MMM-Paris-RATP-PG#36]
Bonjour

J'ai installé le module en le clonant depuis l'adresse https://github.com/MichMich/MagicMirror/

J'ai fait derrière un _sudo npm install unirest_ mais malgré cela j'ai un écran noir dès que j'installe ce module. Ma config est la plus basique :

{	        module: 'MMM-Paris-RATP-PG',
	        position: 'bottom_right',
	        header: 'Connections',
	       config: {
			},
	},

Seriez-vous m'aider svp. Merci

**Comment by da4throux** [comment]
Bonjour,

Le module ne peut-être cloné a partir de l'adresse indiquée.
En supposant que le clonage a été faite a partir du répertoire du module
quand même, la commande d'installation indiquée dans le readme a t elle été
faite ?
Pourquoi faire un npm install de unirest ?
Après ces vérifications, pourriez-vous partagez les logs clients et
serveurs en ne gardant que ce module dans la configuration ?

Merci

Le ven. 17 janv. 2020 à 05:10, franekola <notifications@github.com> a
écrit :

**Comment by agentsteph007** [comment]
Bonjour,

Idem, Installation de Base Sudo, Tuto suivi, Installation de la config Test, et le module ne se charge pas...
Des idées ?

Merci

**Comment by da4throux** [comment]
Hmm... regarder les logs ?

Le mar. 10 mars 2020 à 19:36, agentsteph007 <notifications@github.com> a
écrit :

**Comment by Maquesi** [comment]
Bonjour,
J'avais le même problème,
après avoir dézippé, j'avais comme nom de dossier "MMM-Paris-RATP-PG-master".
Il suffit de le renommer en "MMM-Paris-RATP-PG".

Beau boulot en tout cas, merci!
