### ISSUE TITLE
RER : schedules not available

### ISSUE THREAD

**Issue by Hadr1en** [da4throux/MMM-Paris-RATP-PG#37]
Hello !
I have an issue with the RER B, I don't have the schedules... here the screen and config :
![Capture](https://user-images.githubusercontent.com/38665685/75556949-6f99a080-5a3f-11ea-8839-6e38f924761e.JPG)

`		{
			module: "MMM-Paris-RATP-PG",
			position: "bottom_right",
			header: "Transports",
			config: {
					debug: false,
	lines: [
	  {type: 'buses', line: 512, stations: 'Heurtault', destination: 'A', firstCellColor: '#0055c8'},
	  {type: 'buses', line: 173, stations: 'Heurtault', destination: 'R', firstCellColor: '#dc9600'},
	  {type: 'rers', line: 'B', stations: 'la+plaine+stade+de+france', destination: 'R', label: 'B', firstCellColor: '#7BA3DC'},
	  {type: 'traffic', line: ['rers', 'B'], firstCellColor: 'Blue', lineColor: 'green'},
        ],
			}
		},`

When I try with your example, I get the schedules (for Port Royal), but not for La Plaine Stade de France... I don't know what is the problem as I use the good slug for the station...

Also, what is the number near the line (the one in the circle) ?

Thank you very much ;)

**Comment by da4throux** [comment]
Hi,

the easy part: the number near the line: more details in the readme section "common in all lines", under: showUpdateAge: basically how fresh is the displayed data

looking the main problem right now.

thanks

**Comment by da4throux** [comment]
A few things:
- your configuration seems ok with the readme requirements
- for this kind of data error, the best is first to check the API result (thanks Pierre Grimaud !) so your configuration is asking for: [https://api-ratp.pierre-grimaud.fr/v4/schedules/rers/B/la+plaine+stade+de+france/R](https://api-ratp.pierre-grimaud.fr/v4/schedules/rers/B/la+plaine+stade+de+france/R) : which indeed at the present time sends back: Schedules unavailable.
. The API is working indeed for other stations: [https://api-ratp.pierre-grimaud.fr/v4/schedules/rers/b/chatelet+les+halles/A](https://api-ratp.pierre-grimaud.fr/v4/schedules/rers/b/chatelet+les+halles/A)
. Not sure what to do here...

Out of curiosity, did it ever worked ? or was it the first set up ?

**Comment by da4throux** [comment]
Maybe this is linked to this "Incidents techniques" ?
https://api-ratp.pierre-grimaud.fr/v4/traffic/rers/B
"Dimanche 1 mars 2020 à 17h32, en raison d'une panne de signalisation, le trafic est perturbé de La Plaine-Stade de France vers Saint-Rémy-les-Chevreuse / Robinson sur la ligne B du RER"
Ironically that's when you need them though.

**Comment by Hadr1en** [comment]
Hello !

Yes right after my issue, I tried with Pierre's api on his website and I get the same result, so definitively not linked to your module, sorry ><. 
After few searches, I found that this part (north rer b) is owned by SNCF, so it's why the API don't get the data (because it's only RATP side).
With "http://monrer.fr/?s=LPN" I'm able to get the data, the guy share his code, so if one day you want to implement that :) #suggestion
 
For the number near the line, ok I found the part in the documentation, really sorry to bothered you with that !

Thank you ;)
