### ISSUE TITLE
Loading connections ... Nothing else :(

### ISSUE THREAD

**Issue by Odissine** [da4throux/MMM-Paris-RATP-PG#38]
Hello,

Don't know why but my code doesn't return anything ... still the same message : Loading connections ...
I just want to try with RER Line A ... But nothing :(
Did I miss something ?

```
{
  module: 'MMM-Paris-RATP-PG',
  position: 'top_right',
  header: 'Connections',
  config: {
        debug: false,
	lineDefault: {
	     updateInterval: 1 * 2 * 60 * 1000,
	}, 
	lines : [
		{type: 'rers', line: 'A', stations: 'neuilly+plaisance', destination: 'A', label: 'RER A', firstCellColor: '#7BA3DC'},
		//{type: 'traffic',  line : [ 'rers' ,  'A' ],  firstCellColor : 'Blue',  lineColor : 'red'},
		//{type: 'metros',  line : '9',  stations : 'grands+boulevards', destination : 'A' ,  label : '9',  firstCellColor : '#6ECA97'},
		//{type: 'pluie',  place : '93330',  updateInterval : 1 * 5 * 60 * 1000,  label : 'Paris' ,  iconSize : 0.70},
	],
  },
},
```

**Comment by da4throux** [comment]
this configuration is working fine for me, but the 'pluie' line if uncommented would create problems.
The page from which the information is scratched from probably evolved,
'pluie' option should not be used for the time being.

**Comment by Odissine** [comment]
Je viens de toute reinstaller et tout est ok maintenant ... je ne sais pas pourquoi en revanche mais tant mieux ... Peut etre à cause du node.js ... bref !
SInon petite question ... à quoi sert exactement les ①② ... peut on ne pas les afficher pour n'avoir que les lignes ?

Merci pour ton aide ;)

**Comment by da4throux** [comment]
@Odissine Glad to hear the issue is solved.
Regarding: ①②, it’s described in the Readme, in the paragraph: common to all lines.
It’s: showUpdateAge: optional, boolean, default = true, //add a circled integer such as ①② next to the line name showing the tenths digits of of seconds elapsed since update.
J'ai aussi posté la réponse sur le forum :D, je close !
