### ISSUE TITLE
BusStations Config

### ISSUE THREAD

**Issue by TitouBilou** [da4throux/MMM-Paris-RATP-PG#7]
Hello there,
I can't get the MMM-Paris-RATP-PG module to work on my up to date RasPi. It just shows "Loading connections... " but never update to the traffic information.
Could you please give an example of the "BusStations" array of objects with its four properties? It would be greatly appreciated.
Best regards,
Titou.

**Comment by da4throux** [comment]
Hi there,
it could be: [{ type: 'bus', line: 28, stations: 2550, 70}] 
Breteuil station going to Porte d Orleans according to: [https://api-ratp.pierre-grimaud.fr/v2/bus/28](https://api-ratp.pierre-grimaud.fr/v2/bus/28)
And of course you can put more object in the array.

**Comment by TitouBilou** [comment]
Hi there,

Thanks very much for your quick answer and bringing me the solution. It works now, but in your code, you've missed the word 'destination'. The correct configuration for me is the following one:
busStations : [{ type: 'bus', line: 28, stations: 2550, destination: 70}]
Thanks again,
Best regards,
Titou.
