### ISSUE TITLE
Loading connections

### ISSUE THREAD

**Issue by sdementia** [da4throux/MMM-Paris-RATP-PG#8]
Hi,
Does it is still working ?
I am testing it with no success since yesterday.
The display is still showing "Loading Connections"

I am using the following api line : https://api-ratp.pierre-grimaud.fr/v2/rers/a/stations/376?destination=2

**Comment by da4throux** [comment]
Hi,
no problem on my side, this URL works fine and returns the required data.
I'm wondering:
 - did it worked, and it suddenly stopped, and you are wondering there is a service evolution (and I do not think so, or it was a temporary let down for you)
or
 - it never worked, for you, your trying to set it up, and you are wondering why (setting issue, or service issue): in that case I think it is a setting issue (which should work, I use RER B with no problem). Can you paste your configuration file ?

**Comment by sdementia** [comment]
Hi,
Thanks for your reply. This is my first use of this module, and so, for me, it never worked :)

Here is my config file:

        {
            module: 'MMM-Paris-RATP-PG',
            position: 'bottom_right',
            header: 'Connections',
            config: {
                type: 'rers',
                line: 'A',
                stations: '376',
                destination: '2'
            }
        },

**Comment by da4throux** [comment]
Hi,

that makes sense, your configuration should be more like:
config: {
  busStations: [
           {type: 'rers',
            line: 'A',
            stations: 376,
            destination: 2]
}

**Comment by sdementia** [comment]
Hi,

Great, it works now.
Quicklly said, cause my RER A station is part of SNCF section and the API is not working for this part :(

Anyway, thanks !
